// Code generated by goctl. DO NOT EDIT.
// Source: sys.proto

package server

import (
	"context"

	"go-zero-demo/rpc/sys/internal/logic"
	"go-zero-demo/rpc/sys/internal/svc"
	"go-zero-demo/rpc/sys/sysclient"
)

type SysServer struct {
	svcCtx *svc.ServiceContext
	sysclient.UnimplementedSysServer
}

func NewSysServer(svcCtx *svc.ServiceContext) *SysServer {
	return &SysServer{
		svcCtx: svcCtx,
	}
}

func (s *SysServer) UserInfo(ctx context.Context, in *sysclient.InfoReq) (*sysclient.InfoResp, error) {
	l := logic.NewUserInfoLogic(ctx, s.svcCtx)
	return l.UserInfo(in)
}

func (s *SysServer) UserAdd(ctx context.Context, in *sysclient.UserAddReq) (*sysclient.UserAddResp, error) {
	l := logic.NewUserAddLogic(ctx, s.svcCtx)
	return l.UserAdd(in)
}

// redis增删改查
func (s *SysServer) RedisAdd(ctx context.Context, in *sysclient.RedisReq) (*sysclient.RedisResp, error) {
	l := logic.NewRedisAddLogic(ctx, s.svcCtx)
	return l.RedisAdd(in)
}

func (s *SysServer) RedisDelete(ctx context.Context, in *sysclient.RedisReq) (*sysclient.RedisResp, error) {
	l := logic.NewRedisDeleteLogic(ctx, s.svcCtx)
	return l.RedisDelete(in)
}

func (s *SysServer) RedisUpdate(ctx context.Context, in *sysclient.RedisReq) (*sysclient.RedisResp, error) {
	l := logic.NewRedisUpdateLogic(ctx, s.svcCtx)
	return l.RedisUpdate(in)
}

func (s *SysServer) RedisGet(ctx context.Context, in *sysclient.RedisReq) (*sysclient.RedisResp, error) {
	l := logic.NewRedisGetLogic(ctx, s.svcCtx)
	return l.RedisGet(in)
}

// Kafka生产者演示请求
func (s *SysServer) KafkaProducer(ctx context.Context, in *sysclient.KafkaReq) (*sysclient.KafkaResp, error) {
	l := logic.NewKafkaProducerLogic(ctx, s.svcCtx)
	return l.KafkaProducer(in)
}

// Kafka消费者演示请求
func (s *SysServer) KafkaConsumer(ctx context.Context, in *sysclient.Empty) (*sysclient.KafkaResp, error) {
	l := logic.NewKafkaConsumerLogic(ctx, s.svcCtx)
	return l.KafkaConsumer(in)
}
